```javascript
const missions = [
  {
    numero: 1,
    nom: "Préparer une présentation",
    description: "Concevoir et organiser un support visuel pour communiquer des informations clés à un public.",
    codeCouleur: "BBJV",
    justification: "Principalement analytique (B) avec des aspects créatifs (J) et collaboratifs (V).",
    competencesRequises: "Organisation, créativité, communication",
    niveauDifficulte: 2,
    secteurActivite: "Communication",
    raisonPrincipale: "Nécessite une organisation méthodique et une analyse approfondie du contenu à présenter.",
    raisonSecondaire1: "Implique de la créativité dans la conception visuelle et la présentation des idées de manière engageante.",
    raisonSecondaire2: "Peut nécessiter une collaboration pour rassembler et valider les informations auprès de différentes parties prenantes.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate, sauf en cas de délai serré.",
    exemple1: "Structurer logiquement le contenu de la présentation, analyser les données à inclure.",
    exemple2: "Créer des diapositives visuellement attrayantes, trouver des analogies pour expliquer des concepts complexes.",
    exemple3: "Consulter des collègues pour obtenir des retours sur le contenu et la clarté de la présentation."
  },
  {
    numero: 2,
    nom: "Répondre aux e-mails urgents",
    description: "Traiter rapidement les messages électroniques nécessitant une attention immédiate.",
    codeCouleur: "RRVB",
    justification: "Action rapide (R) avec communication (V) et organisation (B).",
    competencesRequises: "Réactivité, communication écrite, priorisation",
    niveauDifficulte: 2,
    secteurActivite: "Administration",
    raisonPrincipale: "Nécessite une réponse rapide et une prise de décision immédiate.",
    raisonSecondaire1: "Implique de la communication et de la gestion des relations avec les correspondants.",
    raisonSecondaire2: "Demande une organisation pour prioriser les e-mails et répondre de manière structurée.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Répondre immédiatement à un e-mail urgent d'un client.",
    exemple2: "Communiquer clairement et efficacement les informations nécessaires.",
    exemple3: "Organiser les e-mails par priorité pour s'assurer que les plus urgents sont traités en premier."
  },
  {
    numero: 3,
    nom: "Organiser une réunion d'équipe",
    description: "Planifier et coordonner une rencontre entre membres d'une équipe pour discuter de sujets importants.",
    codeCouleur: "VVJB",
    justification: "Collaboration (V) avec créativité (J) et planification (B).",
    competencesRequises: "Leadership, communication, organisation",
    niveauDifficulte: 2,
    secteurActivite: "Management",
    raisonPrincipale: "Nécessite une forte collaboration et interaction entre les membres de l'équipe.",
    raisonSecondaire1: "Peut impliquer de la créativité pour rendre la réunion engageante et productive.",
    raisonSecondaire2: "Demande une planification et une organisation pour structurer la réunion efficacement.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Encourager la participation de tous les membres de l'équipe.",
    exemple2: "Utiliser des techniques de brainstorming pour générer des idées.",
    exemple3: "Préparer un ordre du jour détaillé et structuré."
  },
  {
    numero: 4,
    nom: "Rédiger un rapport mensuel",
    description: "Compiler et analyser les données du mois pour produire un document synthétique.",
    codeCouleur: "BBVR",
    justification: "Analyse (B) avec aspects routiniers (V) et urgence (R).",
    competencesRequises: "Analyse de données, rédaction, synthèse",
    niveauDifficulte: 2,
    secteurActivite: "Gestion",
    raisonPrincipale: "Nécessite une analyse approfondie des données et une rédaction structurée.",
    raisonSecondaire1: "Implique des tâches routinières de collecte et de compilation de données.",
    raisonSecondaire2: "Peut nécessiter une certaine urgence pour respecter les délais de soumission.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser les performances mensuelles et les tendances.",
    exemple2: "Collecter les données mensuelles de différentes sources.",
    exemple3: "Respecter les délais stricts pour la soumission du rapport."
  },
  {
    numero: 5,
    nom: "Analyser les données de performance",
    description: "Examiner en détail les indicateurs de performance pour en tirer des conclusions.",
    codeCouleur: "BBRV",
    justification: "Analyse approfondie (B) avec urgence (R) et routine (V).",
    competencesRequises: "Analyse statistique, interprétation de données, esprit critique",
    niveauDifficulte: 3,
    secteurActivite: "Business Intelligence",
    raisonPrincipale: "Nécessite une analyse détaillée et rigoureuse des données de performance.",
    raisonSecondaire1: "Peut impliquer une certaine urgence pour fournir des insights en temps opportun.",
    raisonSecondaire2: "Implique des tâches routinières de collecte et de traitement des données.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser les KPI pour identifier les tendances et les écarts.",
    exemple2: "Fournir des rapports d'analyse rapidement pour les réunions de direction.",
    exemple3: "Collecter et traiter les données de performance de manière régulière."
  },
  {
    numero: 6,
    nom: "Résoudre un conflit entre collègues",
    description: "Intervenir pour apaiser et trouver une solution à un désaccord entre membres de l'équipe.",
    codeCouleur: "VVRJ",
    justification: "Collaboration (V) avec urgence (R) et créativité (J).",
    competencesRequises: "Médiation, empathie, communication",
    niveauDifficulte: 3,
    secteurActivite: "Ressources Humaines",
    raisonPrincipale: "Nécessite une forte collaboration et empathie pour comprendre les perspectives de chacun.",
    raisonSecondaire1: "Peut impliquer une certaine urgence pour éviter que le conflit n'escalade.",
    raisonSecondaire2: "Peut nécessiter de la créativité pour trouver des solutions innovantes et acceptables par tous.",
    pourquoiPas: "Ne nécessite généralement pas une analyse approfondie ou une organisation méthodique.",
    exemple1: "Écouter activement les parties impliquées pour comprendre leurs préoccupations.",
    exemple2: "Intervenir rapidement pour éviter que le conflit n'affecte l'ensemble de l'équipe.",
    exemple3: "Proposer des solutions créatives pour résoudre le conflit de manière satisfaisante pour tous."
  },
  {
    numero: 7,
    nom: "Planifier un projet à long terme",
    description: "Élaborer une stratégie et un calendrier pour un projet s'étalant sur plusieurs mois.",
    codeCouleur: "BBVJ",
    justification: "Analyse (B) avec collaboration (V) et créativité (J).",
    competencesRequises: "Gestion de projet, planification stratégique, vision à long terme",
    niveauDifficulte: 3,
    secteurActivite: "Gestion de Projet",
    raisonPrincipale: "Nécessite une planification et une analyse détaillée pour structurer le projet.",
    raisonSecondaire1: "Implique une collaboration avec différentes parties prenantes pour définir les objectifs et les ressources.",
    raisonSecondaire2: "Peut nécessiter de la créativité pour trouver des solutions innovantes et efficaces.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Définir les étapes clés et les livrables du projet.",
    exemple2: "Collaborer avec les membres de l'équipe pour allouer les ressources et les responsabilités.",
    exemple3: "Proposer des approches créatives pour surmonter les obstacles potentiels."
  },
  {
    numero: 8,
    nom: "Effectuer une veille concurrentielle",
    description: "Rechercher et analyser les informations sur les concurrents et les tendances du marché.",
    codeCouleur: "BBRJ",
    justification: "Analyse (B) avec urgence (R) et créativité (J).",
    competencesRequises: "Recherche, analyse de marché, pensée stratégique",
    niveauDifficulte: 2,
    secteurActivite: "Marketing",
    raisonPrincipale: "Nécessite une analyse détaillée et rigoureuse des informations concurrentielles.",
    raisonSecondaire1: "Peut impliquer une certaine urgence pour fournir des insights en temps opportun.",
    raisonSecondaire2: "Peut nécessiter de la créativité pour interpréter les données et proposer des stratégies innovantes.",
    pourquoiPas: "Ne nécessite généralement pas de collaboration ou de soutien opérationnel.",
    exemple1: "Analyser les stratégies des concurrents et les tendances du marché.",
    exemple2: "Fournir des rapports de veille concurrentielle rapidement pour les réunions de direction.",
    exemple3: "Proposer des stratégies innovantes basées sur l'analyse concurrentielle."
  },
  {
    numero: 9,
    nom: "Former un nouveau collaborateur",
    description: "Initier et accompagner un nouvel employé dans ses fonctions et l'environnement de travail.",
    codeCouleur: "VVJB",
    justification: "Collaboration (V) avec créativité (J) et organisation (B).",
    competencesRequises: "Pédagogie, communication, patience",
    niveauDifficulte: 2,
    secteurActivite: "Formation",
    raisonPrincipale: "Nécessite une forte collaboration et soutien pour intégrer le nouveau collaborateur.",
    raisonSecondaire1: "Peut impliquer de la créativité pour rendre la formation engageante et efficace.",
    raisonSecondaire2: "Demande une organisation pour structurer le programme de formation.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Accompagner le nouveau collaborateur dans ses premières tâches.",
    exemple2: "Utiliser des méthodes de formation créatives et engageantes.",
    exemple3: "Préparer un programme de formation structuré et détaillé."
  },
  {
    numero: 10,
    nom: "Gérer une situation de crise client",
    description: "Répondre rapidement et efficacement à un problème majeur soulevé par un client.",
    codeCouleur: "RRVJ",
    justification: "Urgence (R) avec collaboration (V) et créativité (J).",
    competencesRequises: "Gestion de crise, service client, résolution de problèmes",
    niveauDifficulte: 3,
    secteurActivite: "Service Client",
    raisonPrincipale: "Nécessite une réponse rapide et une prise de décision immédiate pour gérer la crise.",
    raisonSecondaire1: "Implique une collaboration avec différentes parties prenantes pour résoudre le problème.",
    raisonSecondaire2: "Peut nécessiter de la créativité pour trouver des solutions innovantes et satisfaisantes pour le client.",
    pourquoiPas: "Ne nécessite généralement pas une analyse approfondie ou une organisation méthodique.",
    exemple1: "Répondre immédiatement à une plainte majeure d'un client.",
    exemple2: "Collaborer avec les équipes internes pour trouver une solution rapide.",
    exemple3: "Proposer des solutions créatives pour résoudre le problème de manière satisfaisante pour le client."
  },
  {
    numero: 11,
    nom: "Mettre à jour la documentation interne",
    description: "Réviser et actualiser les documents et procédures internes de l'entreprise.",
    codeCouleur: "BBVR",
    justification: "Analyse (B) avec des aspects routiniers (V) et d'urgence (R).",
    competencesRequises: "Rigueur, attention aux détails, rédaction",
    niveauDifficulte: 2,
    secteurActivite: "Administration",
    raisonPrincipale: "Nécessite une analyse détaillée et rigoureuse des documents existants.",
    raisonSecondaire1: "Implique des tâches routinières de mise à jour et de vérification des informations.",
    raisonSecondaire2: "Peut nécessiter une certaine urgence pour s'assurer que les documents sont à jour.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser les documents existants pour identifier les informations obsolètes.",
    exemple2: "Mettre à jour les informations de manière régulière et systématique.",
    exemple3: "S'assurer que les documents sont à jour avant une date limite importante."
  },
  {
    numero: 12,
    nom: "Participer à une séance de brainstorming",
    description: "Contribuer à une réunion créative pour générer des idées et des solutions.",
    codeCouleur: "JJVB",
    justification: "Créativité (J) avec collaboration (V) et organisation (B).",
    competencesRequises: "Pensée créative, communication, esprit d'équipe",
    niveauDifficulte: 1,
    secteurActivite: "Marketing",
    raisonPrincipale: "Nécessite une forte créativité pour générer des idées nouvelles et innovantes.",
    raisonSecondaire1: "Implique une collaboration avec les autres participants pour échanger et développer les idées.",
    raisonSecondaire2: "Demande une certaine organisation pour structurer la séance de brainstorming.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Proposer des idées originales et innovantes.",
    exemple2: "Échanger et développer les idées avec les autres participants.",
    exemple3: "Structurer la séance de brainstorming pour maximiser l'efficacité."
  },
  {
    numero: 13,
    nom: "Évaluer les performances d'un employé",
    description: "Analyser et donner un retour sur le travail d'un membre de l'équipe.",
    codeCouleur: "BBVJ",
    justification: "Analyse (B) avec des aspects de soutien (V) et de communication (J).",
    competencesRequises: "Évaluation, communication, objectivité",
    niveauDifficulte: 2,
    secteurActivite: "Ressources Humaines",
    raisonPrincipale: "Nécessite une analyse détaillée et objective des performances de l'employé.",
    raisonSecondaire1: "Implique un soutien et une collaboration pour aider l'employé à s'améliorer.",
    raisonSecondaire2: "Demande une communication claire et constructive pour donner un retour efficace.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Analyser les performances de l'employé sur la base de critères objectifs.",
    exemple2: "Collaborer avec l'employé pour identifier les domaines d'amélioration.",
    exemple3: "Communiquer les résultats de manière constructive et motivante."
  },
  {
    numero: 14,
    nom: "Négocier un contrat avec un fournisseur",
    description: "Discuter et convenir des termes d'un contrat avec un partenaire commercial.",
    codeCouleur: "RRJB",
    justification: "Prise de décision rapide (R) avec des aspects de collaboration (J) et d'organisation (B).",
    competencesRequises: "Négociation, communication, stratégie",
    niveauDifficulte: 3,
    secteurActivite: "Achats",
    raisonPrincipale: "Nécessite une prise de décision rapide pour conclure le contrat.",
    raisonSecondaire1: "Implique de la créativité pour trouver des solutions gagnant-gagnant.",
    raisonSecondaire2: "Demande une organisation pour structurer les termes du contrat.",
    pourquoiPas: "Ne nécessite généralement pas de soutien ou de collaboration étroite.",
    exemple1: "Prendre des décisions rapides pour conclure le contrat.",
    exemple2: "Proposer des solutions créatives pour satisfaire les deux parties.",
    exemple3: "Structurer les termes du contrat de manière claire et détaillée."
  },
  {
    numero: 15,
    nom: "Créer un plan de communication",
    description: "Élaborer une stratégie pour communiquer efficacement avec les parties prenantes.",
    codeCouleur: "JJBV",
    justification: "Créativité (J) avec organisation (B) et collaboration (V).",
    competencesRequises: "Rédaction, stratégie, communication",
    niveauDifficulte: 2,
    secteurActivite: "Communication",
    raisonPrincipale: "Nécessite une approche créative pour concevoir des messages efficaces.",
    raisonSecondaire1: "Implique une planification et une organisation détaillées des actions de communication.",
    raisonSecondaire2: "Demande une collaboration avec différentes parties prenantes pour aligner les messages.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Concevoir des messages créatifs et percutants pour différents canaux.",
    exemple2: "Planifier un calendrier détaillé des actions de communication.",
    exemple3: "Collaborer avec les différents départements pour assurer la cohérence des messages."
  },
  {
    numero: 16,
    nom: "Optimiser un processus de travail",
    description: "Analyser et améliorer l'efficacité d'un processus existant.",
    codeCouleur: "BBVJ",
    justification: "Analyse (B) avec des aspects de routine (V) et de créativité (J).",
    competencesRequises: "Analyse de processus, résolution de problèmes, innovation",
    niveauDifficulte: 3,
    secteurActivite: "Gestion",
    raisonPrincipale: "Nécessite une analyse approfondie du processus actuel et de ses inefficacités.",
    raisonSecondaire1: "Implique la compréhension et l'amélioration des tâches routinières.",
    raisonSecondaire2: "Demande de la créativité pour trouver des solutions innovantes.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Analyser en détail chaque étape du processus actuel.",
    exemple2: "Identifier les tâches répétitives qui peuvent être automatisées.",
    exemple3: "Proposer des solutions créatives pour éliminer les goulots d'étranglement."
  },
  {
    numero: 17,
    nom: "Réaliser un audit interne",
    description: "Évaluer les processus internes pour assurer la conformité et l'efficacité.",
    codeCouleur: "BBVR",
    justification: "Analyse (B) avec des aspects de routine (V) et d'urgence (R).",
    competencesRequises: "Rigueur, attention aux détails, évaluation",
    niveauDifficulte: 3,
    secteurActivite: "Audit",
    raisonPrincipale: "Nécessite une analyse détaillée et méthodique des processus et documents.",
    raisonSecondaire1: "Implique des vérifications routinières et systématiques.",
    raisonSecondaire2: "Peut nécessiter une action rapide en cas de découverte de non-conformités.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser en profondeur les processus et la documentation.",
    exemple2: "Effectuer des vérifications systématiques selon une checklist prédéfinie.",
    exemple3: "Signaler et traiter rapidement toute non-conformité découverte."
  },
  {
    numero: 18,
    nom: "Développer une stratégie marketing",
    description: "Élaborer un plan pour promouvoir les produits ou services de l'entreprise.",
    codeCouleur: "BBJR",
    justification: "Analyse (B) avec créativité (J) et aspects d'urgence (R).",
    competencesRequises: "Planification, créativité, analyse de marché",
    niveauDifficulte: 3,
    secteurActivite: "Marketing",
    raisonPrincipale: "Nécessite une analyse approfondie du marché et des données clients.",
    raisonSecondaire1: "Implique de la créativité pour concevoir des campagnes marketing innovantes.",
    raisonSecondaire2: "Peut nécessiter des ajustements rapides en fonction des réactions du marché.",
    pourquoiPas: "Ne nécessite généralement pas de tâches routinières ou de soutien opérationnel.",
    exemple1: "Analyser les tendances du marché et le comportement des consommateurs.",
    exemple2: "Concevoir des campagnes marketing créatives et engageantes.",
    exemple3: "Ajuster rapidement la stratégie en fonction des retours du marché."
  },
  {
    numero: 19,
    nom: "Gérer le budget d'un département",
    description: "Surveiller et contrôler les dépenses d'un service spécifique.",
    codeCouleur: "BBRV",
    justification: "Analyse (B) avec des aspects de routine (R) et de collaboration (V).",
    competencesRequises: "Gestion financière, rigueur, planification",
    niveauDifficulte: 3,
    secteurActivite: "Finance",
    raisonPrincipale: "Nécessite une analyse détaillée des dépenses et des prévisions budgétaires.",
    raisonSecondaire1: "Implique un suivi régulier et des ajustements rapides si nécessaire.",
    raisonSecondaire2: "Demande une collaboration avec les différents membres du département.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser les dépenses par rapport aux prévisions budgétaires.",
    exemple2: "Effectuer des ajustements rapides en cas de dépassement budgétaire.",
    exemple3: "Collaborer avec les responsables du département pour optimiser les dépenses."
  },
  {
    numero: 20,
    nom: "Organiser un événement d'entreprise",
    description: "Planifier et coordonner tous les aspects d'un événement pour l'entreprise.",
    codeCouleur: "VVJB",
    justification: "Collaboration (V) avec des aspects de créativité (J) et d'organisation (B).",
    competencesRequises: "Gestion de projet, communication, créativité",
    niveauDifficulte: 2,
    secteurActivite: "Événementiel",
    raisonPrincipale: "Nécessite une forte collaboration avec différentes parties prenantes.",
    raisonSecondaire1: "Implique de la créativité pour concevoir un événement mémorable.",
    raisonSecondaire2: "Demande une organisation minutieuse de tous les aspects de l'événement.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Coordonner les efforts de différentes équipes (logistique, communication, etc.).",
    exemple2: "Concevoir un thème original et des activités engageantes pour l'événement.",
    exemple3: "Élaborer un planning détaillé et un budget précis pour l'événement."
  },
  {
    numero: 21,
    nom: "Mettre en place un nouveau logiciel",
    description: "Installer et configurer un nouveau système informatique pour l'entreprise.",
    codeCouleur: "BBVJ",
    justification: "Analyse (B) avec des aspects de routine (V) et d'innovation (J).",
    competencesRequises: "Compétences techniques, gestion du changement, formation",
    niveauDifficulte: 3,
    secteurActivite: "IT",
    raisonPrincipale: "Nécessite une analyse approfondie des besoins et une planification détaillée.",
    raisonSecondaire1: "Implique des tâches routinières d'installation et de configuration.",
    raisonSecondaire2: "Demande de la créativité pour adapter le logiciel aux besoins spécifiques de l'entreprise.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Analyser les besoins de l'entreprise et planifier le déploiement du logiciel.",
    exemple2: "Suivre les procédures d'installation et de configuration standard.",
    exemple3: "Trouver des solutions créatives pour intégrer le nouveau logiciel aux systèmes existants."
  },
  {
    numero: 22,
    nom: "Conduire une étude de marché",
    description: "Collecter et analyser des données sur un marché spécifique pour guider les décisions commerciales.",
    codeCouleur: "BBJV",
    justification: "Analyse (B) avec des aspects créatifs (J) et collaboratifs (V).",
    competencesRequises: "Analyse de données, recherche, interprétation",
    niveauDifficulte: 2,
    secteurActivite: "Marketing",
    raisonPrincipale: "Nécessite une analyse approfondie des données collectées.",
    raisonSecondaire1: "Implique de la créativité dans l'interprétation des résultats et la formulation de recommandations.",
    raisonSecondaire2: "Demande une collaboration avec différentes parties prenantes pour collecter les informations.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Analyser les tendances du marché et les comportements des consommateurs.",
    exemple2: "Proposer des insights innovants basés sur les données collectées.",
    exemple3: "Collaborer avec les équipes internes et externes pour obtenir des informations pertinentes."
  },
  {
    numero: 23,
    nom: "Élaborer un plan de formation",
    description: "Concevoir un programme de développement des compétences pour les employés.",
    codeCouleur: "BBJV",
    justification: "Planification (B) avec créativité (J) et aspects collaboratifs (V).",
    competencesRequises: "Pédagogie, analyse des besoins, planification",
    niveauDifficulte: 2,
    secteurActivite: "Ressources Humaines",
    raisonPrincipale: "Nécessite une planification détaillée et une analyse des besoins en formation.",
    raisonSecondaire1: "Implique de la créativité dans la conception des méthodes de formation.",
    raisonSecondaire2: "Demande une collaboration avec différents départements pour identifier les besoins.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Analyser les compétences actuelles et les besoins futurs de l'entreprise.",
    exemple2: "Concevoir des méthodes de formation innovantes et engageantes.",
    exemple3: "Collaborer avec les managers pour identifier les besoins spécifiques de chaque équipe."
  },
  {
    numero: 24,
    nom: "Préparer une proposition commerciale",
    description: "Rédiger une offre détaillée pour un client potentiel.",
    codeCouleur: "JJBV",
    justification: "Créativité (J) avec analyse (B) et aspects collaboratifs (V).",
    competencesRequises: "Rédaction, négociation, analyse des besoins clients",
    niveauDifficulte: 2,
    secteurActivite: "Ventes",
    raisonPrincipale: "Nécessite de la créativité pour présenter l'offre de manière attractive et convaincante.",
    raisonSecondaire1: "Implique une analyse détaillée des besoins du client et des solutions proposées.",
    raisonSecondaire2: "Demande une collaboration avec différentes équipes pour élaborer l'offre.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Concevoir une présentation visuelle attrayante de l'offre.",
    exemple2: "Analyser en détail les besoins du client pour adapter l'offre.",
    exemple3: "Collaborer avec les équipes techniques et financières pour élaborer l'offre."
  },
  {
    numero: 25,
    nom: "Animer une session de team building",
    description: "Organiser et diriger une activité visant à renforcer la cohésion d'équipe.",
    codeCouleur: "JJVB",
    justification: "Créativité (J) avec collaboration (V) et organisation (B).",
    competencesRequises: "Animation de groupe, communication, empathie",
    niveauDifficulte: 2,
    secteurActivite: "Ressources Humaines",
    raisonPrincipale: "Nécessite de la créativité pour concevoir des activités engageantes et originales.",
    raisonSecondaire1: "Implique une forte collaboration et interaction avec les participants.",
    raisonSecondaire2: "Demande une organisation et une planification de l'événement.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Concevoir des activités de team building originales et adaptées à l'équipe.",
    exemple2: "Faciliter les interactions et la communication entre les participants.",
    exemple3: "Planifier le déroulement de la session et préparer le matériel nécessaire."
  },
  {
    numero: 26,
    nom: "Gérer les réseaux sociaux de l'entreprise",
    description: "Créer et publier du contenu sur les plateformes de médias sociaux de l'entreprise.",
    codeCouleur: "JJVB",
    justification: "Créativité (J) avec collaboration (V) et planification (B).",
    competencesRequises: "Rédaction, design, stratégie de contenu",
    niveauDifficulte: 2,
    secteurActivite: "Marketing Digital",
    raisonPrincipale: "Nécessite de la créativité pour produire du contenu engageant et original.",
    raisonSecondaire1: "Implique une collaboration avec différents départements pour obtenir du contenu.",
    raisonSecondaire2: "Demande une planification et une organisation du calendrier de publication.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Créer des visuels attrayants et des textes accrocheurs pour les publications.",
    exemple2: "Collaborer avec les équipes produit et service client pour obtenir du contenu pertinent.",
    exemple3: "Planifier un calendrier éditorial cohérent pour les différentes plateformes."
  },
  {
    numero: 27,
    nom: "Effectuer une analyse de risques",
    description: "Identifier et évaluer les risques potentiels pour l'entreprise.",
    codeCouleur: "BBRV",
    justification: "Analyse (B) avec urgence (R) et aspects collaboratifs (V).",
    competencesRequises: "Analyse, prévision, gestion de crise",
    niveauDifficulte: 3,
    secteurActivite: "Gestion des Risques",
    raisonPrincipale: "Nécessite une analyse approfondie des différents facteurs de risque.",
    raisonSecondaire1: "Implique une certaine urgence pour identifier et traiter les risques critiques.",
    raisonSecondaire2: "Demande une collaboration avec différents départements pour collecter les informations.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser en détail les processus internes et les facteurs externes de risque.",
    exemple2: "Réagir rapidement à l'identification d'un risque majeur.",
    exemple3: "Collaborer avec les différentes équipes pour obtenir une vue d'ensemble des risques."
  },
  {
    numero: 28,
    nom: "Mettre en place un système de suivi qualité",
    description: "Développer et implémenter des processus pour assurer la qualité des produits ou services.",
    codeCouleur: "BBVR",
    justification: "Analyse (B) avec routine (V) et aspects d'urgence (R).",
    competencesRequises: "Gestion de processus, attention aux détails, amélioration continue",
    niveauDifficulte: 3,
    secteurActivite: "Qualité",
    raisonPrincipale: "Nécessite une analyse approfondie des processus existants et des normes de qualité.",
    raisonSecondaire1: "Implique la mise en place de routines de contrôle et de suivi.",
    raisonSecondaire2: "Demande une réactivité en cas de détection de problèmes de qualité.",
    pourquoiPas: "Ne nécessite généralement pas de créativité ou d'innovation.",
    exemple1: "Analyser les processus de production pour identifier les points de contrôle qualité.",
    exemple2: "Mettre en place des procédures de contrôle qualité routinières.",
    exemple3: "Réagir rapidement en cas de détection d'un problème de qualité."
  },
  {
    numero: 29,
    nom: "Préparer un pitch pour des investisseurs",
    description: "Créer et présenter une présentation convaincante pour attirer des investisseurs.",
    codeCouleur: "JJRB",
    justification: "Créativité (J) avec urgence (R) et analyse (B).",
    competencesRequises: "Présentation, persuasion, analyse financière",
    niveauDifficulte: 3,
    secteurActivite: "Finance",
    raisonPrincipale: "Nécessite de la créativité pour présenter le projet de manière convaincante et originale.",
    raisonSecondaire1: "Implique une certaine urgence pour saisir les opportunités de financement.",
    raisonSecondaire2: "Demande une analyse approfondie des données financières et du marché.",
    pourquoiPas: "Ne nécessite généralement pas de collaboration ou de soutien opérationnel.",
    exemple1: "Concevoir une présentation visuelle impactante et un discours persuasif.",
    exemple2: "Adapter rapidement le pitch en fonction des réactions des investisseurs.",
    exemple3: "Analyser en détail les projections financières et les données du marché."
  },
  {
    numero: 30,
    nom: "Réaliser une évaluation environnementale",
    description: "Analyser l'impact environnemental des activités de l'entreprise.",
    codeCouleur: "BBVJ",
    justification: "Analyse (B) avec aspects collaboratifs (V) et créatifs (J).",
    competencesRequises: "Analyse scientifique, réglementation environnementale, reporting",
    niveauDifficulte: 3,
    secteurActivite: "Développement Durable",
    raisonPrincipale: "Nécessite une analyse approfondie des processus de l'entreprise et de leur impact environnemental.",
    raisonSecondaire1: "Implique une collaboration avec différents départements pour collecter les données.",
    raisonSecondaire2: "Demande de la créativité pour proposer des solutions d'amélioration.",
    pourquoiPas: "Ne nécessite généralement pas de prise de décision rapide ou d'action immédiate.",
    exemple1: "Analyser en détail la consommation d'énergie et les émissions de l'entreprise.",
    exemple2: "Collaborer avec les différentes équipes pour obtenir des données précises.",
    exemple3: "Proposer des solutions innovantes pour réduire l'impact environnemental."
  }
];

export default missions;
